# Generated by Django 5.1.6 on 2025-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookings_date',
            field=models.DateTimeField(default='2025-03-05'),
        ),
    ]
