# Generated by Django 5.1.6 on 2025-03-07 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_bookings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookings_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
